#
# Makefile for libudis86, used as disassembler by OPEMU 
#

obj-$(CONFIG_OPEMU)		+= decode.o
obj-$(CONFIG_OPEMU)		+= itab.o
obj-$(CONFIG_OPEMU)		+= syn.o
obj-$(CONFIG_OPEMU)		+= syn-intel.o
obj-$(CONFIG_OPEMU)		+= udis86.o
