#
# Makefile for OPEMU
#

obj-$(CONFIG_OPEMU)		+= libudis86/
obj-$(CONFIG_OPEMU)		+= opemu.o
obj-$(CONFIG_OPEMU)		+= opemu_math.o
obj-$(CONFIG_OPEMU)		+= sse3.o
obj-$(CONFIG_OPEMU)		+= sse42.o
obj-$(CONFIG_OPEMU)		+= ssse3.o
